#!/bin/bash

set -e

error() {
  echo " ! $1"
}

# Check that we have a Staticfile.auth we can use
# echo "Checking Staticfile.auth..."
# if [[ ! -f Staticfile.auth ]]; then
#   error "You are attempting to deploy to an environment that requires a Staticfile.auth, but do not have one locally."
#   error "Please add a Staticfile.auth file to this directory and try again."
#   error
#   error "For information on generating a Staticfile.auth, see"
#   error "http://docs.cloudfoundry.org/buildpacks/staticfile/index.html#basic-auth"
#   exit 1
# fi
# echo "OK!"

bundle install
bower install
bundle exec middleman build
cp nginx.conf ./build/
#cp Staticfile.auth build
cf target -o "${PRODUCT_ORG_NAME:-govuk-paas}" -s "${PRODUCT_SPACE_NAME:-docs}"
cf push "${PRODUCT_APP_NAME:-govuk-paas}"
