#!/usr/bin/env ruby

require 'yaml'

cf_system_dns_root = ENV['CF_API'].sub('https://api.', '')

manifest = YAML.load($stdin.read)
manifest['applications'].each { |app|
  app['env']['DESKPRO_API_KEY'] = ENV['DESKPRO_API_KEY']
  app['routes'] ||= []
  app['routes'] << { 'route' => 'www.' + cf_system_dns_root }
}
puts manifest.to_yaml
