#!/bin/sh

set -eu

PROJECT_DIR=$(cd "$(dirname "$0")/../" && pwd)
CURRENT_DIR=$(pwd)

export CF_APP_NAME=paas-product-page
export DESKPRO_API_KEY=`cat "../secrets/$SECRETS_FILE" | awk '/deskpro_api_key/ { print $2 }'`
export CF_API
export CF_APPS_DOMAIN

${PROJECT_DIR}/release/push-redirect

cd ${PROJECT_DIR}

echo "Creating ${CF_APP_NAME} manifest"
release/generate-manifest \
    < manifest.yml \
    > modified_manifest.yml

echo "Deploying ${CF_APP_NAME} with zero downtime"
cf zero-downtime-push ${CF_APP_NAME} \
    -f modified_manifest.yml

cd ${CURRENT_DIR}
