#!/bin/sh

set -eu

echo "Creating manifest"
export DESKPRO_API_KEY=`cat "../secrets/$SECRETS_FILE" | awk '/deskpro_api_key/ { print $2 }'`
export CF_API
release/generate-manifest \
    < manifest.yml \
    > modified_manifest.yml

echo "Deploy with zero downtime"
cf zero-downtime-push paas-product-page \
    -f modified_manifest.yml
